runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /_ah/spi/.*
  script: project.api

- url: /crons/send_reminder
  script: main.app


libraries:
- name: webapp2
  version: "2.5.2"

- name: endpoints
  version: latest