runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /_ah/spi/.*
  script: project.api

- url: /
  static_files: templates/index.html
  upload: templates/index\.html
  secure: always

- url: /src
  static_dir: static/src

- url: /assets
  static_dir: static/assets

- url: /css
  static_dir: static/css

- url: /crons/send_reminder
  script: main.app


libraries:
- name: webapp2
  version: "2.5.2"

- name: endpoints
  version: latest